version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

      args:
        GIT_COMMIT: ${GIT_COMMIT}

    image: ravindrab5/flask-redis:1.0
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - 9001:5000
    networks:
      - mynet

  redis:
    image: redis:4.0.11-alpine
    networks:
      - mynet
    volumes:
      - mydata:/data

networks:
  mynet:

volumes:
  mydata: